# Generated by Django 5.2.1 on 2025-06-02 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('materias', '0001_initial'),
        ('participacion', '0001_initial'),
        ('trimestre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='materias.materia'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='trimestre.trimestre'),
        ),
    ]
