# Generated by Django 5.2.1 on 2025-06-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
