# Generated by Django 5.2.1 on 2025-06-02 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0001_initial'),
        ('trimestre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestre',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='gestiones.gestion'),
        ),
    ]
