# Generated by Django 5.2.1 on 2025-06-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('carnet', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('especialidad', models.CharField(max_length=255)),
                ('fecha_contratacion', models.DateField()),
            ],
            options={
                'db_table': 'docente',
            },
        ),
    ]
