# Generated by Django 5.2.1 on 2025-06-02 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_asistencia_hora_entrada'),
        ('estudiantes', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='materias.materia'),
        ),
    ]
